apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxuhq2097-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxuhq2097-tenant-component
    app.kubernetes.io/part-of: loadxuhq2097-tenant-app
  name: loadxuhq2097-tenant-component
  namespace: loadxuhq2097-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxuhq2097-tenant-component
    weight: null
status: {}
